[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
excludes = [".agents/**/*.nix", ".github/skills/**/*.nix", ".opencode/skills/**/*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s"]
