[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]
excludes = [".agents/**/*.nix", ".github/skills/**/*.nix", ".opencode/skills/**/*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.yaml", "*.yml", "*.md"]
